### ISSUE TITLE
测试了一下发现报错 读取表xxx失败:missing destination name SRS_ID in *main.ColumnSchema

### ISSUE THREAD

**Issue by axiaoxin** [jiazhoulvke/table2struct#1]

**Comment by jiazhoulvke** [comment]
从这个错误来看应该是你的参数没传对。如果用的是gorm要传`--tag_gorm`，如果用的是sqlx要传`--tag_sqlx`，这样程序才会给你生成对应的tag。具体使用方法请阅读README。

**Comment by axiaoxin** [comment]
用的默认参数 ：table2struct --db_name db --db_pwd pwd
试了下加上 --tag_gorm也一样

这是表结构
<img width="596" alt="image" src="https://user-images.githubusercontent.com/2876405/76814190-1601e600-6835-11ea-8da6-4653b542ab47.png">

**Comment by axiaoxin** [comment]
原因找到了 ，mysql 8.0在information_schema.columns 多了一个SRS_ID字段
